# Default configuration file for wpa_supplicant.conf(5).

#ctrl_interface=/run/wpa_supplicant
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=netdev
#eapol_version=1
#ap_scan=1
#fast_reauth=1
#update_config=1

# Add here your networks.
network={
	ssid="network name"
	#psk="#1#2#3#4" #passowrd generate a psk with wpa_passphrase
	psk=c7b0b5f4b7d7fab18a16b7b1fa4f514dca1edd0f09c46a89058de3a984e32076
}


# IEEE 802.1X with dynamic WEP keys using EAP-PEAP/MSCHAPv2
network={
        ssid="Creativa"
        key_mgmt=WPA-EAP #IEEE8021X
        eap=PEAP
        identity="your user i the network"
        password="storng as usual"
        phase2="auth=MSCHAPV2"
#        ca_cert="/etc/cert/ca.pem"
}
