gui:
  theme: # Catppuccin Mocha (Mauve)
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - grey
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
    cherryPickedCommitBgColor:
      - grey
    cherryPickedCommitFgColor:
      - purple
    unstagedChangesColor:
      - red
    defaultFgColor:
      - white
    searchingActiveBorderColor:
      - yellow
      - bold
    inactiveViewSelectedLineBgColor:
      - bold
    markedBaseCommitFgColor:
      - cyan
    markedBaseCommitBgColor:
      - yellow


  authorColors:
    '*': white


git:
  paging:
      colorArg: always
      pager: git delta --dark --paging=never
