import = [
"~/.config/alacritty/light-theme.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
opacity = 1
title = "terminal"
dynamic_title = true

[font]
size = 13
normal = { family = "terminal-font", style = "Medium" }
bold = { family = "terminal-font", style = "Bold" }
italic = { family = "terminal-font", style = "Medium Italic" }

[keyboard]
bindings = [
{ key = "P", mods = "Control|Shift", action = "Paste" },
{ key = "Y", mods = "Control|Shift", chars = "Copy" },
]
